"""全屋自动化默认规则。阈值与延时可在自动化页面编辑。

光照为原始 ADC 数值；门口超声波独立于室内 motion。
温度和光照使用回差，周期复查确保人员进入时立即响应当前环境。
"""

PRESETS_VERSION = 6

DEFAULT_RULES = [{'preset': 'access_open_door',
  'name': '门禁通过：开门并在10秒后关门',
  'enabled': True,
  'trigger': {'kind': 'event', 'event': 'access_granted'},
  'actions': [{'device': 'door', 'status': 'open'},
              {'device': 'delay', 'seconds': 10},
              {'device': 'door', 'status': 'close'}],
  'cooldown': 2},
 {'preset': 'access_denied_buzzer',
  'name': '门禁被拒：蜂鸣器提示【默认停用】',
  'enabled': False,
  'trigger': {'kind': 'event', 'event': 'access_denied'},
  'actions': [{'device': 'buzzer', 'count': 2, 'on_ms': 250, 'off_ms': 200}],
  'cooldown': 15},
 {'preset': 'smoke_buzzer',
  'name': '检测到烟雾：蜂鸣器报警',
  'enabled': True,
  'trigger': {'kind': 'sensor', 'sensor': 'smoke', 'op': '==', 'value': True},
  'actions': [{'device': 'buzzer', 'count': 5, 'on_ms': 400, 'off_ms': 200}],
  'cooldown': 30},
 {'preset': 'ir_fan_toggle',
  'name': '红外键1：风扇开/关切换（按一次开、再按关）【默认停用】',
  'enabled': False,
  'trigger': {'kind': 'event', 'event': 'ir', 'command': '0x45'},
  'actions': [{'device': 'fan', 'op': 'toggle', 'speed': 60}],
  'cooldown': 2},
 {'preset': 'manual_mark_door',
  'name': '手动操作门：手动优先续期',
  'enabled': True,
  'trigger': {'kind': 'event', 'event': 'manual_control', 'device': 'door'},
  'actions': [{'device': 'state', 'name': 'g:手动优先_门', 'op': 'set', 'value': True}],
  'cooldown': 0},
 {'preset': 'manual_clear_door',
  'name': '手动优先到期：解除门让位',
  'enabled': True,
  'trigger': {'kind': 'sensor', 'sensor': 'g:手动优先_门', 'op': '==', 'value': True, 'hold_sec': 30},
  'actions': [{'device': 'state', 'name': 'g:手动优先_门', 'op': 'set', 'value': False}],
  'cooldown': 5},
 {'preset': 'manual_mark_window',
  'name': '手动操作窗：手动优先续期',
  'enabled': True,
  'trigger': {'kind': 'event', 'event': 'manual_control', 'device': 'window'},
  'actions': [{'device': 'state', 'name': 'g:手动优先_窗', 'op': 'set', 'value': True}],
  'cooldown': 0},
 {'preset': 'manual_clear_window',
  'name': '手动优先到期：解除窗让位',
  'enabled': True,
  'trigger': {'kind': 'sensor', 'sensor': 'g:手动优先_窗', 'op': '==', 'value': True, 'hold_sec': 30},
  'actions': [{'device': 'state', 'name': 'g:手动优先_窗', 'op': 'set', 'value': False}],
  'cooldown': 5},
 {'preset': 'manual_mark_light',
  'name': '手动操作灯：手动优先续期',
  'enabled': True,
  'trigger': {'kind': 'event', 'event': 'manual_control', 'device': 'light'},
  'actions': [{'device': 'state', 'name': 'g:手动优先_灯', 'op': 'set', 'value': True}],
  'cooldown': 0},
 {'preset': 'manual_clear_light',
  'name': '手动优先到期：解除灯让位',
  'enabled': True,
  'trigger': {'kind': 'sensor', 'sensor': 'g:手动优先_灯', 'op': '==', 'value': True, 'hold_sec': 30},
  'actions': [{'device': 'state', 'name': 'g:手动优先_灯', 'op': 'set', 'value': False}],
  'cooldown': 5},
 {'preset': 'manual_mark_fan',
  'name': '手动操作风扇：手动优先续期',
  'enabled': True,
  'trigger': {'kind': 'event', 'event': 'manual_control', 'device': 'fan'},
  'actions': [{'device': 'state', 'name': 'g:手动优先_风扇', 'op': 'set', 'value': True}],
  'cooldown': 0},
 {'preset': 'manual_clear_fan',
  'name': '手动优先到期：解除风扇让位',
  'enabled': True,
  'trigger': {'kind': 'sensor', 'sensor': 'g:手动优先_风扇', 'op': '==', 'value': True, 'hold_sec': 30},
  'actions': [{'device': 'state', 'name': 'g:手动优先_风扇', 'op': 'set', 'value': False}],
  'cooldown': 5},
 {'preset': 'manual_mark_ac',
  'name': '手动操作空调：手动优先续期',
  'enabled': True,
  'trigger': {'kind': 'event', 'event': 'manual_control', 'device': 'ac'},
  'actions': [{'device': 'state', 'name': 'g:手动优先_空调', 'op': 'set', 'value': True}],
  'cooldown': 0},
 {'preset': 'manual_clear_ac',
  'name': '手动优先到期：解除空调让位',
  'enabled': True,
  'trigger': {'kind': 'sensor', 'sensor': 'g:手动优先_空调', 'op': '==', 'value': True, 'hold_sec': 30},
  'actions': [{'device': 'state', 'name': 'g:手动优先_空调', 'op': 'set', 'value': False}],
  'cooldown': 5},
 {'preset': 'temp_hot',
  'name': '有人：高于26°C开风扇',
  'enabled': True,
  'trigger': {'kind': 'interval', 'seconds': 2},
  'conditions': [{'sensor': 'sensor_fresh', 'op': '==', 'value': True},
                 {'sensor': 'g:有人在家', 'op': '==', 'value': True},
                 {'sensor': 'g:手动优先_风扇', 'op': '==', 'value': False},
                 {'sensor': 'g:允许自动开风扇', 'op': '==', 'value': True},
                 {'sensor': 'temperature', 'op': '>', 'value': 26}],
  'actions': [{'device': 'fan', 'speed': 100}],
  'match': 'all',
  'cooldown': 0},
 {'preset': 'temp_cool',
  'name': '有人：不高于25°C关风扇',
  'enabled': True,
  'trigger': {'kind': 'interval', 'seconds': 2},
  'conditions': [{'sensor': 'sensor_fresh', 'op': '==', 'value': True},
                 {'sensor': 'g:有人在家', 'op': '==', 'value': True},
                 {'sensor': 'g:手动优先_风扇', 'op': '==', 'value': False},
                 {'sensor': 'temperature', 'op': '<=', 'value': 25}],
  'actions': [{'device': 'fan', 'speed': 0}],
  'match': 'all',
  'cooldown': 0},
 {'preset': 'light_dark',
  'name': '有人：光照低于200开灯',
  'enabled': True,
  'trigger': {'kind': 'interval', 'seconds': 2},
  'conditions': [{'sensor': 'sensor_fresh', 'op': '==', 'value': True},
                 {'sensor': 'g:有人在家', 'op': '==', 'value': True},
                 {'sensor': 'g:手动优先_灯', 'op': '==', 'value': False},
                 {'sensor': 'light', 'op': '<', 'value': 200}],
  'actions': [{'device': 'light', 'status': 'on', 'brightness': 100}],
  'match': 'all',
  'cooldown': 0},
 {'preset': 'light_off',
  'name': '有人：光照达到300关灯',
  'enabled': True,
  'trigger': {'kind': 'interval', 'seconds': 2},
  'conditions': [{'sensor': 'sensor_fresh', 'op': '==', 'value': True},
                 {'sensor': 'g:有人在家', 'op': '==', 'value': True},
                 {'sensor': 'g:手动优先_灯', 'op': '==', 'value': False},
                 {'sensor': 'light', 'op': '>=', 'value': 300}],
  'actions': [{'device': 'light', 'status': 'off', 'brightness': 0}],
  'match': 'all',
  'cooldown': 0},
 {'preset': 'presence_motion',
  'name': '室内检测到人：有人在家',
  'enabled': True,
  'trigger': {'kind': 'interval', 'seconds': 2},
  'conditions': [{'sensor': 'sensor_fresh', 'op': '==', 'value': True},
                 {'sensor': 'motion', 'op': '==', 'value': True}],
  'actions': [{'device': 'state', 'name': 'g:有人在家', 'op': 'set', 'value': True},
              {'device': 'state', 'name': 'g:全屋模式', 'op': 'set', 'value': 'auto'}],
  'match': 'all',
  'cooldown': 0},
 {'preset': 'presence_timeout',
  'name': '室内连续120秒无人：离家',
  'enabled': True,
  'trigger': {'kind': 'sensor', 'sensor': 'motion', 'op': '==', 'value': False, 'hold_sec': 120},
  'actions': [{'device': 'state', 'name': 'g:有人在家', 'op': 'set', 'value': False},
              {'device': 'state', 'name': 'g:全屋模式', 'op': 'set', 'value': 'away'}],
  'cooldown': 0},
 {'preset': 'away_close_all',
  'name': '无人：关灯和风扇',
  'enabled': True,
  'trigger': {'kind': 'interval', 'seconds': 2},
  'conditions': [{'sensor': 'sensor_fresh', 'op': '==', 'value': True},
                 {'sensor': 'g:有人在家', 'op': '==', 'value': False},
                 {'sensor': 'motion', 'op': '==', 'value': False}],
  'actions': [{'device': 'light', 'status': 'off', 'brightness': 0}, {'device': 'fan', 'speed': 0}],
  'match': 'all',
  'cooldown': 0},
 {'preset': 'rain_window',
  'name': '雨水或烟雾：关窗',
  'enabled': True,
  'trigger': {'kind': 'interval', 'seconds': 2},
  'conditions': [{'sensor': 'rain', 'op': '==', 'value': True},
                 {'sensor': 'smoke', 'op': '==', 'value': True}],
  'actions': [{'device': 'window', 'status': 'close'}],
  'match': 'any',
  'cooldown': 0},
 {'preset': 'window_normal',
  'name': '无雨无烟：恢复45°',
  'enabled': True,
  'trigger': {'kind': 'interval', 'seconds': 2},
  'conditions': [{'sensor': 'sensor_fresh', 'op': '==', 'value': True},
                 {'sensor': 'rain', 'op': '==', 'value': False},
                 {'sensor': 'smoke', 'op': '==', 'value': False}],
  'actions': [{'device': 'window', 'status': 'normal'}],
  'match': 'all',
  'cooldown': 0},
 {'preset': 'touch_open_close',
  'name': '触摸：开门并在10秒后关门',
  'enabled': True,
  'trigger': {'kind': 'sensor', 'sensor': 'touch', 'op': '==', 'value': True},
  'actions': [{'device': 'door', 'status': 'open'},
              {'device': 'delay', 'seconds': 10},
              {'device': 'door', 'status': 'close'}],
  'cooldown': 0}]
