"""全屋自动化默认规则。阈值与延时可在自动化页面编辑。

光照为原始 ADC 数值；门口超声波独立于室内 motion。
温度和光照使用回差，周期复查确保人员进入时立即响应当前环境。
"""

import copy

PRESETS_VERSION = 9

DEFAULT_RULES = [{'preset': 'access_open_door',
  'name': '门禁通过：开门并在10秒后关门',
  'enabled': True,
  'trigger': {'kind': 'event', 'event': 'access_granted'},
  'actions': [{'device': 'door', 'status': 'open'},
              {'device': 'delay', 'seconds': 10},
              {'device': 'door', 'status': 'close'}],
  'cooldown': 2},
 {'preset': 'access_denied_buzzer',
  'name': '门禁被拒：蜂鸣器提示【默认停用】',
  'enabled': False,
  'trigger': {'kind': 'event', 'event': 'access_denied'},
  'actions': [{'device': 'buzzer', 'count': 2, 'on_ms': 250, 'off_ms': 200}],
  'cooldown': 15},
 {'preset': 'smoke_buzzer',
  'name': '检测到烟雾：蜂鸣器报警',
  'enabled': True,
  'trigger': {'kind': 'sensor', 'sensor': 'smoke', 'op': '==', 'value': True},
  'actions': [{'device': 'buzzer', 'count': 5, 'on_ms': 400, 'off_ms': 200}],
  'cooldown': 30},
 {'preset': 'ir_remote_light_toggle',
  'name': '红外键1：灯开/关切换',
  'enabled': True,
  'trigger': {'kind': 'event', 'event': 'ir', 'command': '0x45'},
  'conditions': [{'sensor': 'light_status', 'op': '==', 'value': 'on'}],
  'actions': [{'device': 'state', 'name': 'g:手动优先_灯', 'op': 'set', 'value': True},
              {'device': 'light', 'status': 'off', 'brightness': 0}],
  'else_actions': [{'device': 'state', 'name': 'g:手动优先_灯', 'op': 'set', 'value': True},
                   {'device': 'light', 'status': 'on', 'brightness': 100}],
  'match': 'all',
  'cooldown': 1},
 {'preset': 'ir_remote_fan_toggle',
  'name': '红外键2：风扇开/关切换',
  'enabled': True,
  'trigger': {'kind': 'event', 'event': 'ir', 'command': '0x46'},
  'conditions': [{'sensor': 'fan_speed', 'op': '>', 'value': 0}],
  'actions': [{'device': 'state', 'name': 'g:手动优先_风扇', 'op': 'set', 'value': True},
              {'device': 'fan', 'op': 'off', 'speed': 60}],
  'else_actions': [{'device': 'state', 'name': 'g:手动优先_风扇', 'op': 'set', 'value': True},
                   {'device': 'fan', 'op': 'on', 'speed': 60}],
  'match': 'all',
  'cooldown': 1},
 {'preset': 'ir_remote_door_toggle',
  'name': '红外键3：门开/关切换',
  'enabled': True,
  'trigger': {'kind': 'event', 'event': 'ir', 'command': '0x47'},
  'conditions': [{'sensor': 'door_status', 'op': '==', 'value': 'open'}],
  'actions': [{'device': 'state', 'name': 'g:手动优先_门', 'op': 'set', 'value': True},
              {'device': 'door', 'status': 'close'}],
  'else_actions': [{'device': 'state', 'name': 'g:手动优先_门', 'op': 'set', 'value': True},
                   {'device': 'door', 'status': 'open'}],
  'match': 'all',
  'cooldown': 1},
 {'preset': 'ir_remote_window_toggle',
  'name': '红外键4：窗开/关切换',
  'enabled': True,
  'trigger': {'kind': 'event', 'event': 'ir', 'command': '0x44'},
  'conditions': [{'sensor': 'window_status', 'op': '==', 'value': 'open'}],
  'actions': [{'device': 'state', 'name': 'g:手动优先_窗', 'op': 'set', 'value': True},
              {'device': 'window', 'status': 'close'}],
  'else_actions': [{'device': 'state', 'name': 'g:手动优先_窗', 'op': 'set', 'value': True},
                   {'device': 'window', 'status': 'open'}],
  'match': 'all',
  'cooldown': 1},
 {'preset': 'manual_mark_door',
  'name': '手动操作门：手动优先续期',
  'enabled': True,
  'trigger': {'kind': 'event', 'event': 'manual_control', 'device': 'door'},
  'actions': [{'device': 'state', 'name': 'g:手动优先_门', 'op': 'set', 'value': True}],
  'cooldown': 0},
 {'preset': 'manual_clear_door',
  'name': '手动优先到期：解除门让位',
  'enabled': True,
  'trigger': {'kind': 'sensor', 'sensor': 'g:手动优先_门', 'op': '==', 'value': True, 'hold_sec': 30},
  'actions': [{'device': 'state', 'name': 'g:手动优先_门', 'op': 'set', 'value': False}],
  'cooldown': 5},
 {'preset': 'manual_mark_window',
  'name': '手动操作窗：手动优先续期',
  'enabled': True,
  'trigger': {'kind': 'event', 'event': 'manual_control', 'device': 'window'},
  'actions': [{'device': 'state', 'name': 'g:手动优先_窗', 'op': 'set', 'value': True}],
  'cooldown': 0},
 {'preset': 'manual_clear_window',
  'name': '手动优先到期：解除窗让位',
  'enabled': True,
  'trigger': {'kind': 'sensor', 'sensor': 'g:手动优先_窗', 'op': '==', 'value': True, 'hold_sec': 30},
  'actions': [{'device': 'state', 'name': 'g:手动优先_窗', 'op': 'set', 'value': False}],
  'cooldown': 5},
 {'preset': 'manual_mark_light',
  'name': '手动操作灯：手动优先续期',
  'enabled': True,
  'trigger': {'kind': 'event', 'event': 'manual_control', 'device': 'light'},
  'actions': [{'device': 'state', 'name': 'g:手动优先_灯', 'op': 'set', 'value': True}],
  'cooldown': 0},
 {'preset': 'manual_clear_light',
  'name': '手动优先到期：解除灯让位',
  'enabled': True,
  'trigger': {'kind': 'sensor', 'sensor': 'g:手动优先_灯', 'op': '==', 'value': True, 'hold_sec': 30},
  'actions': [{'device': 'state', 'name': 'g:手动优先_灯', 'op': 'set', 'value': False}],
  'cooldown': 5},
 {'preset': 'manual_mark_fan',
  'name': '手动操作风扇：手动优先续期',
  'enabled': True,
  'trigger': {'kind': 'event', 'event': 'manual_control', 'device': 'fan'},
  'actions': [{'device': 'state', 'name': 'g:手动优先_风扇', 'op': 'set', 'value': True}],
  'cooldown': 0},
 {'preset': 'manual_clear_fan',
  'name': '手动优先到期：解除风扇让位',
  'enabled': True,
  'trigger': {'kind': 'sensor', 'sensor': 'g:手动优先_风扇', 'op': '==', 'value': True, 'hold_sec': 30},
  'actions': [{'device': 'state', 'name': 'g:手动优先_风扇', 'op': 'set', 'value': False}],
  'cooldown': 5},
 {'preset': 'manual_mark_ac',
  'name': '手动操作空调：手动优先续期',
  'enabled': True,
  'trigger': {'kind': 'event', 'event': 'manual_control', 'device': 'ac'},
  'actions': [{'device': 'state', 'name': 'g:手动优先_空调', 'op': 'set', 'value': True}],
  'cooldown': 0},
 {'preset': 'manual_clear_ac',
  'name': '手动优先到期：解除空调让位',
  'enabled': True,
  'trigger': {'kind': 'sensor', 'sensor': 'g:手动优先_空调', 'op': '==', 'value': True, 'hold_sec': 30},
  'actions': [{'device': 'state', 'name': 'g:手动优先_空调', 'op': 'set', 'value': False}],
  'cooldown': 5},
 {'preset': 'temp_hot',
  'name': '有人：高于26°C开风扇',
  'enabled': True,
  'trigger': {'kind': 'interval', 'seconds': 2},
  'conditions': [{'sensor': 'sensor_fresh', 'op': '==', 'value': True},
                 {'sensor': 'g:有人在家', 'op': '==', 'value': True},
                 {'sensor': 'g:手动优先_风扇', 'op': '==', 'value': False},
                 {'sensor': 'g:允许自动开风扇', 'op': '==', 'value': True},
                 {'sensor': 'temperature', 'op': '>', 'value': 26}],
  'actions': [{'device': 'fan', 'speed': 100}],
  'match': 'all',
  'cooldown': 0},
 {'preset': 'temp_cool',
  'name': '有人：不高于25°C关风扇',
  'enabled': True,
  'trigger': {'kind': 'interval', 'seconds': 2},
  'conditions': [{'sensor': 'sensor_fresh', 'op': '==', 'value': True},
                 {'sensor': 'g:有人在家', 'op': '==', 'value': True},
                 {'sensor': 'g:手动优先_风扇', 'op': '==', 'value': False},
                 {'sensor': 'temperature', 'op': '<=', 'value': 25}],
  'actions': [{'device': 'fan', 'speed': 0}],
  'match': 'all',
  'cooldown': 0},
 {'preset': 'light_dark',
  'name': '有人：光照偏暗（暗/亮二态）开灯',
  'enabled': True,
  'trigger': {'kind': 'interval', 'seconds': 2},
  'conditions': [{'sensor': 'sensor_fresh', 'op': '==', 'value': True},
                 {'sensor': 'g:有人在家', 'op': '==', 'value': True},
                 {'sensor': 'g:手动优先_灯', 'op': '==', 'value': False},
                 {'sensor': 'light_dark', 'op': '==', 'value': True}],
  'actions': [{'device': 'light', 'status': 'on', 'brightness': 100}],
  'match': 'all',
  'cooldown': 0},
 {'preset': 'light_off',
  'name': '有人：光照偏亮（暗/亮二态）关灯',
  'enabled': True,
  'trigger': {'kind': 'interval', 'seconds': 2},
  'conditions': [{'sensor': 'sensor_fresh', 'op': '==', 'value': True},
                 {'sensor': 'g:有人在家', 'op': '==', 'value': True},
                 {'sensor': 'g:手动优先_灯', 'op': '==', 'value': False},
                 {'sensor': 'light_dark', 'op': '==', 'value': False}],
  'actions': [{'device': 'light', 'status': 'off', 'brightness': 0}],
  'match': 'all',
  'cooldown': 0},
 {'preset': 'presence_motion',
  'name': '室内检测到人：有人在家',
  'enabled': True,
  'trigger': {'kind': 'interval', 'seconds': 2},
  'conditions': [{'sensor': 'sensor_fresh', 'op': '==', 'value': True},
                 {'sensor': 'motion', 'op': '==', 'value': True}],
  'actions': [{'device': 'state', 'name': 'g:有人在家', 'op': 'set', 'value': True},
              {'device': 'state', 'name': 'g:全屋模式', 'op': 'set', 'value': 'auto'}],
  'match': 'all',
  'cooldown': 0},
 {'preset': 'presence_timeout',
  'name': '室内连续120秒无人：离家',
  'enabled': True,
  'trigger': {'kind': 'sensor', 'sensor': 'motion', 'op': '==', 'value': False, 'hold_sec': 120},
  'actions': [{'device': 'state', 'name': 'g:有人在家', 'op': 'set', 'value': False},
              {'device': 'state', 'name': 'g:全屋模式', 'op': 'set', 'value': 'away'}],
  'cooldown': 0},
 {'preset': 'away_close_all',
  'name': '无人：关灯和风扇',
  'enabled': True,
  'trigger': {'kind': 'interval', 'seconds': 2},
  'conditions': [{'sensor': 'sensor_fresh', 'op': '==', 'value': True},
                 {'sensor': 'g:有人在家', 'op': '==', 'value': False},
                 {'sensor': 'motion', 'op': '==', 'value': False},
                 {'sensor': 'g:手动优先_灯', 'op': '==', 'value': False},
                 {'sensor': 'g:手动优先_风扇', 'op': '==', 'value': False}],
  'actions': [{'device': 'light', 'status': 'off', 'brightness': 0}, {'device': 'fan', 'speed': 0}],
  'match': 'all',
  'cooldown': 0},
 {'preset': 'rain_window',
  'name': '雨水或烟雾：关窗',
  'enabled': True,
  'trigger': {'kind': 'interval', 'seconds': 2},
  'conditions': [{'sensor': 'rain', 'op': '==', 'value': True},
                 {'sensor': 'smoke', 'op': '==', 'value': True}],
  'actions': [{'device': 'window', 'status': 'close'}],
  'match': 'any',
  'cooldown': 0},
 {'preset': 'window_normal',
  'name': '无雨无烟：恢复45°',
  'enabled': True,
  'trigger': {'kind': 'interval', 'seconds': 2},
  'conditions': [{'sensor': 'sensor_fresh', 'op': '==', 'value': True},
                 {'sensor': 'rain', 'op': '==', 'value': False},
                 {'sensor': 'smoke', 'op': '==', 'value': False},
                 # 与风扇/灯同一口径：手动优先期内不让位，避免用户刚把窗户调到
                 # 想要的角度、下一拍就被自动规则拨回 45°（见 R2）。
                 # rain_window（安全关窗）**故意不带**这条 —— 手动优先不能压过安全。
                 {'sensor': 'g:手动优先_窗', 'op': '==', 'value': False}],
  'actions': [{'device': 'window', 'status': 'normal'}],
  'match': 'all',
  'cooldown': 0},
 {'preset': 'touch_open_close',
  'name': '触摸：开门并在10秒后关门',
  'enabled': True,
  'trigger': {'kind': 'event', 'event': 'touch_on'},
  'actions': [{'device': 'door', 'status': 'open'},
              {'device': 'delay', 'seconds': 10},
              {'device': 'door', 'status': 'close'}],
  'cooldown': 0}]


# ── R4：内容修过、但只允许「用户没改过」才覆盖的内置预设 ──
# 迁移（engine._migrate_legacy_rules）会拿磁盘上的规则与本表的历史内置内容逐字段
# 比较（忽略 id/name/enabled）：一致的才换成新版；用户改动过的一律原样保留并告警。
# 这样既能让修复生效，又不会像以前那样无条件覆盖用户对预设的定制。
_BY_PRESET = {p["preset"]: p for p in DEFAULT_RULES if p.get("preset")}


def _legacy_light_variant(preset: str, op: str, value: int) -> dict:
    """v7 及更早的 light_dark/light_off：末条条件是比较原始 ADC 的 light 阈值。"""
    rule = copy.deepcopy(_BY_PRESET[preset])
    rule["conditions"] = [dict(c) for c in rule["conditions"][:-1]]
    rule["conditions"].append({"sensor": "light", "op": op, "value": value})
    return rule


def _legacy_window_variant() -> dict:
    """v8 的 window_normal：还没有「g:手动优先_窗 让位」这条条件。"""
    rule = copy.deepcopy(_BY_PRESET["window_normal"])
    rule["conditions"] = [dict(c) for c in rule["conditions"]
                          if c.get("sensor") != "g:手动优先_窗"]
    return rule


PRESET_LEGACY_CONTENT = {
    "light_dark": [_legacy_light_variant("light_dark", "<", 400)],
    "light_off": [_legacy_light_variant("light_off", ">", 700)],
    "window_normal": [_legacy_window_variant()],
}
