; Module A — Sensor Node
; 只负责采集传感器数据并上报，不做任何业务判断。

[env:uno]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 115200

build_flags =
    -Isrc

lib_deps =
    adafruit/DHT sensor library@^1.4.6
    miguelbalboa/MFRC522@^1.4.11
    Arduino-IRremote/IRremote@^4.3.0
